### ISSUE TITLE
align_offset does not write coffset

### ISSUE THREAD

**Issue by biochem-fan** [taw10/crystfel#13]
Even with `--out-of-plane`, refined `coffset` is not written to the output geometry file.

The cause is this check:
https://github.com/taw10/crystfel/blob/16f4ffd1445c09d9e22e941930686243d1214105/libcrystfel/src/datatemplate.c#L2564-L2566

**Comment by taw10** [comment]
Hmm, works in my tests.  The check is so that the coffset stays at the top of the output file (vs listed for every panel), if it was that way in the input.  Any chance you could send a geometry file which gets corrupted, e.g. with a simple `adjust_detector -i in.geom -o out.geom` (which will use the same code path without altering anything)?

**Comment by biochem-fan** [comment]
Sure. I will make a minimum reproducible example tomorrow.

**Comment by biochem-fan** [comment]
Could you please test this?

```
align_detector -g input.geom -o output.geom --out-of-plane -l1 test.bin
```

[align.zip](https://github.com/taw10/crystfel/files/15222066/align.zip)

**Comment by taw10** [comment]
Oh!  The problem isn't so much with writing the geometry file, but with something else.  If you have a top-level `coffset`, then move only some panels, the `coffset` should now be specific to each panel.  Fix coming up...

**Comment by biochem-fan** [comment]
@taw10 Thanks for the patch. It does output `coffset`s but the values do not make sense unfortunately.

First, I would like to have the group_all shift in `clen` or the global `coffset`, but `clen` remains unchanged and there is no global `coffset`.

Next, individual `coffset`s are different from `z-translation` values written in the log file (see above).

```
$ grep coffset test.geom 
q1/coffset = -0.000184
q2/coffset = -0.000141
q3/coffset = -0.000184
q4/coffset = -0.000100
q5/coffset = -0.000165
q6/coffset = -0.000160
q7/coffset = -0.000191
q8/coffset = -0.000210
```

The log for the first three panels are:

```
Group all:
    x-translation +0.402610 mm
    y-translation -0.080583 mm
    z-translation +0.098321 mm
    x-rotation -0.028239 deg
    y-rotation -0.354392 deg
Group q1:
    x-translation +0.177990 mm
    y-translation +0.009914 mm
    z-translation -0.070802 mm
    x-rotation +0.114678 deg
    y-rotation +0.321578 deg
    z-rotation -0.020110 deg
Group q2:
    x-translation +0.199630 mm
    y-translation +0.140630 mm
    z-translation -0.030641 mm
    x-rotation +0.178115 deg
    y-rotation +0.077693 deg
    z-rotation +0.024323 deg
Group q3:
    x-translation -0.115230 mm
    y-translation -0.069046 mm
    z-translation +0.036583 mm
    x-rotation -0.075120 deg
    y-rotation +0.157300 deg
    z-rotation -0.090894 deg
```

I expect `q1/coffset` to be +0.098321 mm -0.070802 mm = 0.027519 mm = 0.000027519 m but the geometry file says "0.000184" (m).

More worryingly, even `-l0` sets **different** `coffset` values to individual panels!

Because "+z is the beam direction, and points along the beam", detector tilt and twist (i.e. the z components in `fs` and `ss`) do not matter, do they?

```
Group all:
    x-translation +0.148960 mm
    y-translation -0.078616 mm
    z-translation -0.203500 mm
    x-rotation -0.056718 deg
    y-rotation -0.139120 deg

$ grep coffset test.geom 
q1/coffset = 0.000250
q2/coffset = 0.000224
q3/coffset = 0.000204
q4/coffset = 0.000178
q5/coffset = 0.000229
q6/coffset = 0.000203
q7/coffset = 0.000183
q8/coffset = 0.000157
```

**Comment by taw10** [comment]
It looks strange, but I think everything here is as expected.  Don't forget that the x/y (out of plane) rotations also change the z-position of the panel corners, i.e. the `coffset`, even at refinement level zero.  The rotations are done about the centre of the panel group.  Note that the top-level rotation center might not coincide with the beam, but it still works because there are enough other degrees of freedom.

It's not clever enough to put the overall z-shift into the top level `clen` or `coffset`.  The `clen` might be a reference to an image header, so that's not a good place, and there can only be one `coffset` for each panel - multiple values are not additive.  However, the changes should be small.

The refinement is only weakly sensitive to the out-of-plane twists of the detector, but not totally insensitive.  Do you suspect it needs an "out-of-plane but shifts only, not x/y-rotation" mode?  As noted, there are still some avenues for improving the stability of the refinement.

**Comment by biochem-fan** [comment]
> Don't forget that the x/y (out of plane) rotations also change the z-position of the panel corners, i.e. the coffset, even at refinement level zero. The rotations are done about the centre of the panel group.

Aha! I wasn't aware of this. This makes sense.

> Do you suspect it needs an "out-of-plane but shifts only, not x/y-rotation" mode?

Actually I have already tried this myself.
https://github.com/biochem-fan/cheetah/wiki/CrystFEL-0.11#can-we-refine-the-detector-distance

I am not sure whether this improves the stability, but this is conceptually good, at least. The detector distance is adjustable (the detector slides along a rail) and has a higher degree of uncertainty than tilt and twist (which are not movable, at least at SACLA).

In this mode without x/y rotations , I confirmed that `coffset`s values corresponds to the printed z-translations, so your fix is correct. Thanks.

> there are still some avenues for improving the stability of the refinement

I like your idea posted in https://gitlab.desy.de/thomas.white/crystfel/-/issues/92#note_959205.
This would enable multiple cycles of Millepede refinement without re-runing `indexamajig` many times. In my preliminary tests (not in the wiki), when the initial geometry was not very good, more cycles of `indexamajig` followed by Millepede were necessary before convergence than with `geoptimiser`. I guess this is caused by the linear approximation. This would also allow calculation of RMSDs (work and free). At the moment, I have to use `geoptimiser` to calculate RMSDs to see if the geometry is really improving.

**Comment by taw10** [comment]
Thanks for the thorough testing!  I'm sorry that you seem to run into all those problems.  Or perhaps it's just that you actually bother to report them...

Interesting observation that Millepede takes longer to converge from a bad geometry than geoptimiser.  It could be because of the linear approximation, but I would rather guess it's because there's currently too much freedom in the cell parameter part of the refinement, like you observe at the bottom of your notes.  This is exactly what I want to improve in a future version.  Eventually it should be equivalent to a full DIALS refinement - it is mathematically the same, just zillions of times faster.

About RMSDs: the spot-to-prediction distances (also excitation errors) are actually already in the Mille files.  They can be read e.g. using this [small Julia package](https://gitlab.desy.de/thomas.white/millepedeii.jl), but I will try to find a more convenient way.

If you run multiple cycles of Millepede (or geoptimiser) refinement, don't you have to re-run indexing anyway?  You can re-run `align_detector` with different parameters (hierarchy levels etc) with the same Mille files, but once you change the geometry, you have to re-calculate everything.  The input geometry to `align_detector` isn't part of the refinement calculation, it's only updated according to the results.

**Comment by biochem-fan** [comment]
> About RMSDs: the spot-to-prediction distances (also excitation errors) are actually already in the Mille files. They can be read e.g. using this [small Julia package](https://gitlab.desy.de/thomas.white/millepedeii.jl), but I will try to find a more convenient way.

If there are multiple `.bin` files, how should I combine them?

> If you run multiple cycles of Millepede (or geoptimiser) refinement, don't you have to re-run indexing anyway? You can re-run align_detector with different parameters (hierarchy levels etc) with the same Mille files, but once you change the geometry, you have to re-calculate everything. The input geometry to align_detector isn't part of the refinement calculation, it's only updated according to the results.

In DIALS, when parameters (geometry and cell) are updated, predictions and gradients are re-calculated within `dials.refine`. On the other hand, gradients at a fixed point in the parameter landscape are pre-calculated and passed to Millepede and never updated. Thus, if initial parameters were off in highly non-linear directions (e.g. large rotations rather than translations), one has to run many cycles of `indexamajig` followed by `align_detector` (see also [this](https://www.desy.de/~kleinwrt/MP2/doc/html/draftman_page.html#sssec-nonlin)). `geoptimiser` also does not update predictions but it uses `arccos` to find a rotation (if the description in the paper still applies).

> Interesting observation that Millepede takes longer to converge from a bad geometry than geoptimiser. It could be because of the linear approximation, but I would rather guess it's because there's currently too much freedom in the cell parameter part of the refinement, like you observe at the bottom of your notes.

Anyway, now that most bugs are fixed, I will rerun my tests (probably during the next week).

**Comment by biochem-fan** [comment]
> here is a probably-not-very-helpful summary

Thank you! This is very useful information.

> I want to make sure we're on the same page about when to re-run indexing:

Yes, I understand these.

My point is about how the changes, especially rotations, are parameterized. If you fit rotations directly with arccos, as in `geoptimiser`, you can fit an arbitrarily large rotation in one step. On the other hand, if you express it as $\theta_{current} + \Delta\theta$ and solve linear equations about $\Delta\theta$, one refinement step is valid only within this linear approximation, where $\sin\Delta\theta \approx \Delta\theta$. Beyond this radius, the shift is inaccurate and we need more steps until convergence. This means we have to run more `indexamajig` cycles.

**Comment by taw10** [comment]
I'd be very surprised if the small angle approximation is what limits the convergence.  The error is tiny.  According to my quick calculation, less than 1 pixel for a worst case scenario (very outer reflection on a 16M detector an in-plane rotation of nearly 2°).  I think that the other effects we've talked about, geometry errors getting "soaked up" by the wrong degrees of freedom, will be much more significant.  But it's true, the linear approximation is one of the trade-offs here.

**Comment by biochem-fan** [comment]
In case someone else is looking for:

I wrote a jiffy Python script to calculate RMSDs from multiple CrystFEL 0.11 Millepede bin files.
https://gist.github.com/biochem-fan/f508c830a516245f8c8ee97fee34702e

This works only for a single level detectors at the moment.
